import { Sour_Gummy } from 'next/font/google';
import Footer from "./components/Footer";
import Header from "./components/Header";

const sourGummy = Sour_Gummy({ weight: '400', subsets: ["latin"] })

import "./globals.css";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr" style={{ minHeight: '100dvh' }}>
      <body className={` ${sourGummy.className}`}>
        <Header />
        <section className="main">
          {children}
        </section>
        <Footer />
      </body>
    </html>
  );
}
